name: Build Chrome Extension
on:
  push
  
jobs:
    build-chrome:
        runs-on: ubuntu-latest
        steps:
        
            # checkout repo
            - uses: actions/checkout@v3
            
            # get certificate
            - name: Get Chrome Certificate
              env:
                CHROME_CERTIFICATE: ${{ secrets.CHROME_CERTIFICATE }}
              run: |
                echo $CHROME_CERTIFICATE > cert.pem
            
            # build chrome extension
            - name: Build Chrome Extension
              uses: GabrielBB/xvfb-action@v1
              with:
                run: |
                    google-chrome --headless --pack-extension=./ --pack-extension-key=cert.pem
                
            # test extension was built
            - name: Extension Build Check
              run: |
                ls
                ls authenticator-chrome.ctx